### ISSUE TITLE
Entrega 3 - Exclusividad

### ISSUE THREAD

**Issue by diegosanchez** [Tomymanoukian/AyPIII_TP2#116]
No veo casos de uso donde se ejemplifique el uso de `Exclusividad`.

**Comment by Tomymanoukian** [comment]
Hola Diego, buenas tardes. En el test "AsignacionDePuntosTest" (https://github.com/Tomymanoukian/AyPIII_TP2/blob/master/src/main/test/edu/fiuba/algo3/modelo/AsignacionDePuntosTest.java) se encuentran implementados los casos de uso de Exclusividad.
